package com.example.handlers;

import com.sap.cds.services.handler.EventHandler;
import com.sap.cds.services.handler.annotations.On;
import com.sap.cds.services.handler.annotations.ServiceName;
import com.sap.cds.ql.Select;
import com.sap.cds.ql.Update;
import com.sap.cds.services.cds.CqnService;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/*
 * These imports come from the classes generated by cds-maven-plugin
 * (execution id: cds.generate, basePackage: cds.gen).
 *
 * They are produced during "mvn generate-sources" (or any later phase such as
 * "mvn compile" / "mvn spring-boot:run") and will NOT exist before the first
 * Maven build.  If your IDE shows red underlines before the first build, run:
 *
 *   mvn generate-sources
 *
 * …and then refresh/reimport the project in your IDE.
 */
import cds.gen.booksservice.AddBookContext;
import cds.gen.booksservice.BooksService_;
import cds.gen.booksservice.Books;
import cds.gen.booksservice.TotalStockContext;

import java.math.BigDecimal;
import java.util.List;

/**
 * Event handler for the BooksService.
 *
 * Provides custom logic for:
 *  - addBook  (action)
 *  - totalStock (function)
 */
@Component
@ServiceName(BooksService_.CDS_NAME)
public class BooksHandler implements EventHandler {

    private static final Logger log = LoggerFactory.getLogger(BooksHandler.class);

    @Autowired
    private CqnService db;

    /**
     * Handles the addBook action.
     * Creates a new Books record in-memory and returns it.
     */
    @On(event = AddBookContext.CDS_NAME)
    public void onAddBook(AddBookContext ctx) {
        log.info("addBook called: title={}, author={}", ctx.getTitle(), ctx.getAuthor());

        Books newBook = Books.create();
        newBook.setTitle(ctx.getTitle());
        newBook.setAuthor(ctx.getAuthor());
        newBook.setPrice(ctx.getPrice() != null ? ctx.getPrice() : BigDecimal.ZERO);
        newBook.setStock(0);

        ctx.setResult(newBook);
        ctx.setCompleted();
    }

    /**
     * Handles the totalStock() function.
     * Returns the sum of the stock field across all Books.
     */
    @On(event = TotalStockContext.CDS_NAME)
    public void onTotalStock(TotalStockContext ctx) {
        log.info("totalStock called");

        List<Books> books = db.run(Select.from(BooksService_.BOOKS)).listOf(Books.class);
        int total = books.stream()
                .mapToInt(b -> b.getStock() != null ? b.getStock() : 0)
                .sum();

        log.info("Total stock across all books: {}", total);
        ctx.setResult(total);
        ctx.setCompleted();
    }
}
