stages:
  build:
    buildTool: "mta"
    buildDescriptor: "mta.yaml"
    buildToolVersion: "MBTJ17N22"

  additionalTests:
    npmTests:
      buildDescriptor: "package.json"
      npmScript: "test"
